version: '3'

dotenv: ['.env', '.env.local']

env:
  TAG:
    sh: git log -n 1 --format=%h

tasks:
  deploy:
    desc: Deploy to production
    cmds:
      - docker compose up --build --detach
  deploy-app:
    desc: Deploy to production
    cmds:
      - docker compose up app --build --detach
  up:
    desc: Start production
    cmds:
      - docker compose up --detach
  down:
    desc: Stop production
    cmds:
      - docker compose down
  restart:
    desc: Restart in production
    cmds:
      - docker compose restart
  ps:
    desc: Do ps in production
    cmds:
      - docker compose ps
  build:
    desc: Do build in production
    cmds:
      - docker compose build
  build-*:
    desc: Do build in production
    vars:
      SERVICE: '{{index .MATCH 0}}'
    cmds:
      - docker compose build {{.SERVICE}}
  log-*:
    desc: Show log in production
    vars:
      SERVICE: '{{index .MATCH 0}}'
    cmds:
      - docker compose logs {{.SERVICE}}
  download_model:
    desc: Download Vosk model
    cmds:
      - curl -sSfL -o /tmp/vosk-model-ja.zip https://alphacephei.com/vosk/models/vosk-model-ja-0.22.zip
      - unzip /tmp/vosk-model-ja.zip -d /var/vosk/
      - rm /tmp/vosk-model-ja.zip
  decrypt_prompt:
    desc: Decrypt prompt file
    cmds:
      - age -d -i $PROMPT_PRIVATE_KEY_PATH src/prompt/initial.txt.age > src/prompt/initial.txt
  encrypt_prompt:
    desc: Encrypt prompt file
    cmds:
      - age -R $PROMPT_PUBLIC_KEY_PATH src/prompt/initial.txt > src/prompt/initial.txt.age
