version: '3'

dotenv: ['.env', 'core/.env']

env:
  GIT_HASH:
    sh: git rev-parse HEAD

vars:
  DOCKER_COMPOSE:
    sh: |
      if [ -z "${DOCKER_HOST}" ]; then
        echo "docker compose -f compose.yaml -f compose.dev.yaml"
      else
        echo "docker compose"
      fi

tasks:
  deploy:
    desc: Deploy to production
    cmds:
      - '{{.DOCKER_COMPOSE}} up --build --detach'
  deploy-*:
    desc: Deploy a service
    vars:
      SERVICE: '{{index .MATCH 0}}'
    cmds:
      - '{{.DOCKER_COMPOSE}} up {{.SERVICE}} --build --detach'
  up:
    desc: Start production
    cmds:
      - '{{.DOCKER_COMPOSE}} up --detach --remove-orphans'
  rebuild-*:
    desc: Start production
    vars:
      SERVICE: '{{index .MATCH 0}}'
    cmds:
      - '{{.DOCKER_COMPOSE}} up --detach --build {{.SERVICE}}'
  down:
    desc: Stop production
    cmds:
      - '{{.DOCKER_COMPOSE}} down'
  restart:
    desc: Restart in production
    cmds:
      - '{{.DOCKER_COMPOSE}} restart'
  wait:
    desc: Wait for core service health
    cmds:
      - |
        until [ "$({{.DOCKER_COMPOSE}} ps --format json | jq -r .Health)" == "healthy" ]; do
          echo "waiting for core service to be healthy..."
          sleep 5
        done
      - echo "Core service is healthy!"
  ps:
    desc: Do ps in production
    cmds:
      - '{{.DOCKER_COMPOSE}} ps'
  exec-*:
    desc: Execute command in production
    cmds:
      - '{{.DOCKER_COMPOSE}} exec -it {{index .MATCH 0}} sh'
  build:
    desc: Do build in production
    cmds:
      - '{{.DOCKER_COMPOSE}} build'
  build-*:
    desc: Do build in production
    vars:
      SERVICE: '{{index .MATCH 0}}'
    cmds:
      - '{{.DOCKER_COMPOSE}} build {{.SERVICE}}'
  log-*:
    desc: Show log in production
    vars:
      SERVICE: '{{index .MATCH 0}}'
    cmds:
      - '{{.DOCKER_COMPOSE}} logs --tail=100 {{.SERVICE}}'
  decrypt_prompt:
    desc: Decrypt prompt file
    cmds:
      - cd core && node --env-file .env scripts/decrypt_prompt.js
  encrypt_prompt:
    desc: Encrypt prompt file
    cmds:
      - cd core && node --env-file .env scripts/encrypt_prompt.js
  mcp/build:
    desc: Build all MCP servers
    deps:
      - mcp/build-concept-graph
      - mcp/build-scheduler
      - mcp/build-weather
      - mcp/build-metrics
      - mcp/build-rss
  mcp/build-*:
    desc: Build a MCP server
    vars:
      NAME: '{{index .MATCH 0}}'
    cmds:
      - mkdir -p core/bin
      - cd mcp/{{.NAME}} && cargo build --release
      - cp mcp/{{.NAME}}/target/release/{{.NAME}} core/bin/
  mcp/inspect-*:
    desc: Inspect a MCP server
    vars:
      NAME: '{{index .MATCH 0}}'
    cmds:
      - npx @modelcontextprotocol/inspector -e TZ=Asia/Tokyo -e DATA_DIR=/tmp/data core/bin/{{.NAME}}
  setup:
    desc: Setup development environment
    cmds:
      - cd core && pnpm install
      - task: mcp/build
  backup:
    desc: Backup all data
    cmds:
      - task core/backup
      - task sandbox/backup
      - task memgraph/backup
  core/backup:
    desc: Backup core data
    vars:
      DOCKER_HOST: ${DOCKER_HOST}
      TIMESTAMP:
        sh: date +%Y%m%d%H%M%S
      BACKUP_DIR: ${BACKUP_DIR:-./backup}
    cmds:
      - mkdir -p {{.BACKUP_DIR}}
      - '{{.DOCKER_COMPOSE}} cp core:/data /tmp/tsuki-backup-{{.TIMESTAMP}}'
      - tar czf {{.BACKUP_DIR}}/tsuki-backup-{{.TIMESTAMP}}.tar.gz -C /tmp/tsuki-backup-{{.TIMESTAMP}} .
      - rm -rf /tmp/tsuki-backup-{{.TIMESTAMP}}
  memgraph/backup:
    desc: Backup memgraph database
    vars:
      BACKUP_DIR: ${BACKUP_DIR:-./backup}/memgraph
      BACKUP_FILE_PATH:
        sh: 'echo "CREATE SNAPSHOT;" | {{.DOCKER_COMPOSE}} exec -T memgraph mgconsole -output_format csv | tail -1 | tr -d \"'
    cmds:
      - mkdir -p {{.BACKUP_DIR}}
      - '{{.DOCKER_COMPOSE}} cp memgraph:{{.BACKUP_FILE_PATH}} {{.BACKUP_DIR}}/'
  sandbox/backup:
    desc: Backup sandbox data
    vars:
      TIMESTAMP:
        sh: date +%Y%m%d%H%M%S
    cmds:
      - '{{.DOCKER_COMPOSE}} cp sandbox:/memory /tmp/tsuki-backup-sandbox'
      - tar czf ./backup/tsuki-sandbox-backup-{{.TIMESTAMP}}.tar.gz -C /tmp/tsuki-backup-sandbox .
      - rm -rf /tmp/tsuki-backup-sandbox
  memgraph/restore/latest:
    desc: Restore latest memgraph database
    vars:
      BACKUP_FILE_NAME:
        sh: 'ls -t ${BACKUP_DIR:-./backup}/memgraph | head -1'
    cmds:
      - task: memgraph/restore/{{.BACKUP_FILE_NAME}}
  memgraph/restore/*:
    desc: Restore memgraph database
    vars:
      BACKUP_DIR: ${BACKUP_DIR:-./backup}/memgraph
      BACKUP_FILE_NAME: '{{index .MATCH 0}}'
    cmds:
      - '{{.DOCKER_COMPOSE}} cp {{.BACKUP_DIR}}/{{.BACKUP_FILE_NAME}} memgraph:/data/snapshots/{{.BACKUP_FILE_NAME}}'
      - '{{.DOCKER_COMPOSE}} exec -u root memgraph chown memgraph:memgraph /data/snapshots/{{.BACKUP_FILE_NAME}}'
      - 'echo "RECOVER SNAPSHOT ''/data/snapshots/{{.BACKUP_FILE_NAME}}'' FORCE;" | {{.DOCKER_COMPOSE}} exec -T memgraph mgconsole'
