version: '3'

dotenv: ['.env', '.env.local']

env:
  TAG:
    sh: git log -n 1 --format=%h

tasks:
  deploy:
    desc: Deploy to production
    cmds:
      - sbt docker:stage
      - docker compose up --build --detach
  up:
    desc: Start production
    cmds:
      - docker compose up --detach
  down:
    desc: Stop production
    cmds:
      - docker compose down
  restart:
    desc: Restart in production
    cmds:
      - docker compose restart
  ps:
    desc: Do ps in production
    cmds:
      - docker compose ps
  build:
    desc: Do build in production
    cmds:
      - docker compose build
