[main]
database_type = "file"
database_url = "/var/memory/history.json"

[core]
openai_model = "gpt-4o"
max_output_tokens = 10000
dify_sandbox_host = "ssrf-proxy:8194"

[scheduler]
resolution_secs = 10
session_reset_schedule = "0 0 19 * * *"

[web]
port = 2953

[recognizer]
mumble_host = "mumble-server"
mumble_port = 64738
vosk_model_path = "/var/model/vosk-model-ja-0.22"
monitor_interval_millisecs = 100
silence_timeout_millisecs = 500

[speak]
voicevox_endpoint = "http://voicevox-engine:50021"
voicevox_speaker_index = 58
