version: '3'

dotenv: ['.env']

tasks:
  test-scenario/*:
    desc: Run core + client scenario after clearing core/data
    vars:
      SCENARIO: '{{index .MATCH 0}}'
    cmds:
      - rm -rf ./data
      - pnpm tsx ./tests/runner.ts ./tests/client/run.ts ./tests/client/scenarios/{{.SCENARIO}}.yaml
