version: '3'

dotenv: ['.env']

tasks:
  reset-data:
    desc: Reset core/data to initial state
    vars:
      DATA_BACKUP: '{{.DEBUG_INIT_DATA_BACKUP}}'
    cmds:
      - rm -rf ./data
      - mkdir -p ./data
      - tar -xzf {{.DATA_BACKUP}} -C ./data
  test-scenario/*:
    desc: Run core + client scenario after clearing core/data
    vars:
      SCENARIO: '{{index .MATCH 0}}'
    cmds:
      - rm -rf ./data
      - task -t ../Taskfile.yaml local/clean-data
      - pnpm tsx ./tests/runner.ts ./tests/client/run.ts ./tests/client/scenarios/{{.SCENARIO}}.yaml
  tts/demo:
    desc: demonstrate TTS
    cmds:
      - |
        curl -sS -X POST "http://localhost:{{.PORT}}/tts" \
          -H "Authorization: {{.USER}}:{{.WEB_AUTH_TOKEN}}" \
          -H "Content-Type: application/json" \
          -d '{"message":"こんにちは♪聞こえますか～？"}' \
          --output out.wav
