name: Test

on:
  push:
    paths:
      - "core/**"
      - ".github/workflows/test.yml"
  pull_request:
    paths:
      - "core/**"
      - ".github/workflows/test.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./core
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        run: rustup update stable && rustup default stable
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            core -> target
      - name: Run tests
        run: cargo test
