name: Test

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Prepare included files
      run: |
        cp conf/default.toml conf/local.toml
        touch src/service_account_key.json
        touch src/prompt/initial.txt
    - name: Install dependencies
      run: sudo apt-get install -y cmake protobuf-compiler
    - name: Install vosk
      run: |
        curl -sSLf -o /tmp/vosk.zip https://github.com/alphacep/vosk-api/releases/download/v0.3.45/vosk-linux-$(arch)-0.3.45.zip
        unzip -qj -d /tmp /tmp/vosk.zip vosk-linux-x86_64-0.3.45/libvosk.so
        sudo install /tmp/libvosk.so /usr/local/lib
        rm /tmp/vosk.zip /tmp/libvosk.so
    - name: Setup Rust
      run: rustup update nightly && rustup default nightly
    - name: Build
      env:
        OPENAI_API_KEY: xxx
        WEB_AUTH_TOKEN: xxx
        DIFY_SANDBOX_API_KEY: xxx
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
