name: Test

on:
  push:
    paths-ignore:
      - 'gui/**'
  pull_request:
    paths-ignore:
      - 'gui/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GIT_HASH: ${{ github.sha }}

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./core
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        cache-dependency-path: 'core/package-lock.json'
    - name: Install dependencies
      run: npm ci
    - name: Type check
      run: npx tsc --noEmit
    - name: Lint
      run: npx eslint .
    - name: Build check
      run: npm run build
    - name: Run tests
      env:
        OPENAI_API_KEY: xxx
        WEB_AUTH_TOKEN: xxx
        DIFY_SANDBOX_API_KEY: xxx
        PROMPT_PRIVATE_KEY: xxx
      run: npm test
